language: rust

dist: trusty

rust:
  - stable
  - beta
  - nightly

script:
  - rustc --version -v
  - cargo --version -v
  - cargo build

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

notifications:
  email:
    on_success: never
    on_failure: change
