git:
  depth: 3

language: rust

dist: bionic

rust:
  - stable
  - nightly

script:
  - rustc --version -v
  - cargo --version -v
  - cargo build

matrix:
  allow_failures:
    - rust: nightly

notifications:
  email:
    on_success: never
    on_failure: change
