name: publish

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Publish binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.arch }}
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.arch }} --locked
      - name: Package
        run: |
          version=$(basename ${{ github.ref }})
          pkg=tmux-tanlog-${version}-${{ matrix.arch }}
          mkdir pack
          cp target/${{ matrix.arch }}/release/tmux-tanlog pack/${pkg}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: pack/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
